#pragma checksum "..\..\..\..\MVVM\View\ReviewSystemView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "02CFC262CD504AF00EF6433C248B1B624F589926E5B28579CB74ED975237A8AC"
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using Review_Reminder.MVVM.Model;
using Review_Reminder.MVVM.View;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Review_Reminder.MVVM.View {
    
    
    /// <summary>
    /// ReviewSystemView
    /// </summary>
    public partial class ReviewSystemView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 36 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ReviewContentBox;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddBtn;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DeleteBtn;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CategorySettingBox;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SettingBtn;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button InitializeBtn;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel CategorySelectPanel;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category1Yellow;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category1Green;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category1Red;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category2Green;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category2Yellow;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category2Red;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category3Green;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category3Yellow;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category3Red;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category4Green;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category4Yellow;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category4Red;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category5Green;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category5Yellow;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category5Red;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category6Green;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category6Yellow;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Category6Red;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category1Name;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category2Name;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category3Name;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category4Name;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category5Name;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category6Name;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category1Percent;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category2Percent;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category3Percent;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category4Percent;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category5Percent;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Category6Percent;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Review_Reminder;component/mvvm/view/reviewsystemview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ReviewContentBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.AddBtn = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            this.AddBtn.Click += new System.Windows.RoutedEventHandler(this.add_btn_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.DeleteBtn = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            this.DeleteBtn.Click += new System.Windows.RoutedEventHandler(this.delete_btn_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.CategorySettingBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.SettingBtn = ((System.Windows.Controls.Button)(target));
            
            #line 46 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            this.SettingBtn.Click += new System.Windows.RoutedEventHandler(this.setting_btn_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.InitializeBtn = ((System.Windows.Controls.Button)(target));
            
            #line 48 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            this.InitializeBtn.Click += new System.Windows.RoutedEventHandler(this.initialize_btn_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.CategorySelectPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 8:
            
            #line 52 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Click += new System.Windows.RoutedEventHandler(this.category_btn_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 54 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Click += new System.Windows.RoutedEventHandler(this.category_btn_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 56 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Click += new System.Windows.RoutedEventHandler(this.category_btn_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 58 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Click += new System.Windows.RoutedEventHandler(this.category_btn_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 60 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Click += new System.Windows.RoutedEventHandler(this.category_btn_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 62 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Click += new System.Windows.RoutedEventHandler(this.category_btn_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 64 "..\..\..\..\MVVM\View\ReviewSystemView.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Click += new System.Windows.RoutedEventHandler(this.category_btn_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.Category1Yellow = ((System.Windows.Controls.Image)(target));
            return;
            case 16:
            this.Category1Green = ((System.Windows.Controls.Image)(target));
            return;
            case 17:
            this.Category1Red = ((System.Windows.Controls.Image)(target));
            return;
            case 18:
            this.Category2Green = ((System.Windows.Controls.Image)(target));
            return;
            case 19:
            this.Category2Yellow = ((System.Windows.Controls.Image)(target));
            return;
            case 20:
            this.Category2Red = ((System.Windows.Controls.Image)(target));
            return;
            case 21:
            this.Category3Green = ((System.Windows.Controls.Image)(target));
            return;
            case 22:
            this.Category3Yellow = ((System.Windows.Controls.Image)(target));
            return;
            case 23:
            this.Category3Red = ((System.Windows.Controls.Image)(target));
            return;
            case 24:
            this.Category4Green = ((System.Windows.Controls.Image)(target));
            return;
            case 25:
            this.Category4Yellow = ((System.Windows.Controls.Image)(target));
            return;
            case 26:
            this.Category4Red = ((System.Windows.Controls.Image)(target));
            return;
            case 27:
            this.Category5Green = ((System.Windows.Controls.Image)(target));
            return;
            case 28:
            this.Category5Yellow = ((System.Windows.Controls.Image)(target));
            return;
            case 29:
            this.Category5Red = ((System.Windows.Controls.Image)(target));
            return;
            case 30:
            this.Category6Green = ((System.Windows.Controls.Image)(target));
            return;
            case 31:
            this.Category6Yellow = ((System.Windows.Controls.Image)(target));
            return;
            case 32:
            this.Category6Red = ((System.Windows.Controls.Image)(target));
            return;
            case 33:
            this.Category1Name = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 34:
            this.Category2Name = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.Category3Name = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 36:
            this.Category4Name = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 37:
            this.Category5Name = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 38:
            this.Category6Name = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.Category1Percent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            this.Category2Percent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 41:
            this.Category3Percent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.Category4Percent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.Category5Percent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 44:
            this.Category6Percent = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

