#pragma checksum "..\..\..\..\MVVM\View\TodolistReminder.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "A9CC71C0986632C69567ED23F391DCC0CBB832CD97E341C63EB9DBF0F9E29E45"
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using Review_Reminder.MVVM.View;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Review_Reminder.MVVM.View {
    
    
    /// <summary>
    /// TodolistReminder
    /// </summary>
    public partial class TodolistReminder : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 25 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Separator seper;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image firstl;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image sndl;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image thdl;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image forthl;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock first;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock snd;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock thd;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock forth;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock subjectlabel;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock todoname;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Review_Reminder;component/mvvm/view/todolistreminder.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\MVVM\View\TodolistReminder.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.seper = ((System.Windows.Controls.Separator)(target));
            return;
            case 2:
            this.firstl = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.sndl = ((System.Windows.Controls.Image)(target));
            return;
            case 4:
            this.thdl = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.forthl = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.first = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.snd = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.thd = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.forth = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.subjectlabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.todoname = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

